### PR TITLE
Update unlock.py

### PR DESCRIPTION
**Pull request by bbb0**
- implemented the "store progress" by taskula
- IMEI check and warning
- minor speed improvement
- auto stop when reach 17 digits
- tell if it could find the code

Use it in RAM drive or else it can wear out your HDD / SSD (so many write cycle)!

### CODE REVIEW

**Comment by E440QF** [comment]
does this version support linux?

**Comment by Doping11** [comment]
Is it possible to speed up the script by using nvidia cuda cores?

**Comment by E440QF** [comment]
I'm not 100% sure but I'm pretty confident that the bottleneck is the phone, not the pc

**Comment by bbb0** [comment]
The communication between the phone and the PC takes some time, it does not matter if you use CUDA cores or not. The current speed improvement is only a few millisecs (does not count the increment every step), you can barely notice that.

**Comment by bbb0** [comment]
> does this version support linux?

I did not try it on Linux, but if you installed adb and python, then it should run (the fastboot syntax is the same on Windows and Linux).

**Comment by Doping11** [comment]
I found a way to speed up the script. I replaced the included "fastboot.exe" with that one of "minimal adb fastboot 1.4".

**Pull request closed without merging**
